[WIP]implement user story #65
tsukuba-pbl/NavigationFor_iOS pull request #19
Opened 2017-08-16 02:29 UTC by Minajun

# ユーザーストーリー
- #65曲がるべき場所（交差点など）で、右折左折直進などの指示を画面上で確認できる
- taiga(https://tree.taiga.io/project/minajun-tsukuba-rd-project-2017-ume-systems/us/65?milestone=146595)

## TODO
- [x] BLE Localization のパーミッションを追加
- [ ] #76周辺にあるビーコンを取得する
- [ ] #77取得したビーコンのUUID,minor,major値を取得する
- [ ] #78取得したビーコンのRSSIを取得する
- [ ] #79ナビゲーションデータを読み込み
- [ ] #80指定されたビーコンに近づいた時にあらかじめ設定した方向指示を表示する
- [ ] #81ナビゲーションデータのフォーマットを決める

# 終了条件
- [ ] ナビゲーションが開始できる
- [ ] 指定された交差点に近づいた時に、設定したナビゲーションが画面上に表示される

# 前提条件
- [ ] ナビゲーションデータは事前に保存されている

2017-08-18 12:50 UTC, ferretdayo commented on NavigationForiOS/NavigationViewController.swift
> +    private func locationManager(manager: CLLocationManager!, didStartMonitoringForRegion region: CLRegion!) {
NavigationViewControllerだけにこんなにlocationManagerとか直に書いちゃうとコントローラが肥大化しちゃうので，BeaconServiceみたいな感じにBeaconの処理をまとめたクラスを作ったほうがいいと思う．

2017-08-18 12:50 UTC, ferretdayo commented on NavigationForiOS/NavigationViewController.swift
> +    private func locationManager(manager: CLLocationManager!, didDetermineState state: CLRegionState, forRegion inRegion: CLRegion!) {
ここも

2017-08-18 12:50 UTC, ferretdayo commented on NavigationForiOS/NavigationViewController.swift
> +    private func locationManager(manager: CLLocationManager!, didEnterRegion region: CLRegion!) {
ここも

2017-08-18 12:51 UTC, ferretdayo commented on NavigationForiOS/NavigationViewController.swift
> +    private func locationManager(manager: CLLocationManager!, didStartMonitoringForRegion region: CLRegion!) {
言ってないところもちょっと考えて綺麗にしてみよう

2017-08-19 07:29 UTC, ferretdayo requested changes
errorはslackにあげたりしたいね。とりあえずエラーはprintせず放置でいいかも

2017-08-19 07:29 UTC, ferretdayo commented on NavigationForiOS/BeaconService.swift
> +
これ不要ー

2017-08-19 07:29 UTC, ferretdayo commented on NavigationForiOS/BeaconService.swift
> +        switch (status) {
swiftの場合break不要なん？今外なので調べてないけど

2017-08-19 07:29 UTC, ferretdayo commented on NavigationForiOS/BeaconService.swift
> +        print("locationManager: didDetermineState \(state)")
不要

2017-08-19 07:29 UTC, ferretdayo commented on NavigationForiOS/BeaconService.swift
> +        print("didEnterRegion");
不要

2017-08-19 07:29 UTC, ferretdayo commented on NavigationForiOS/BeaconService.swift
> +
不要

2017-08-19 07:29 UTC, ferretdayo commented on NavigationForiOS/NavigationService.swift
> +                }
print不要

2017-08-19 07:29 UTC, ferretdayo commented on NavigationForiOS/NavigationService.swift
> +                print(error)
print不要

2017-08-19 13:47 UTC, Minajun commented
テストコードで
isOnNavigationPoint（）
をテストすると、関数内で使用しているviewControllerのメンバ変数planUUIDに参照できなくなって
テストコードが動かなくなる

2017-08-19 14:07 UTC, Minajun commented
あとでリファクタリングすればいいや

2017-08-20 00:47 UTC, Minajun commented
これでテスト通るはず

2017-08-20 03:22 UTC, ferretdayo requested changes
😣

2017-08-20 03:22 UTC, ferretdayo commented on NavigationForiOS/BeaconService.swift
> +        NSLog("Init BeaconService")
いらなーい

2017-08-20 03:22 UTC, ferretdayo commented on NavigationForiOS/BeaconService.swift
> +            NSLog("CLAuthorizedStatus: \(status)")
いらーないかな

2017-08-20 03:22 UTC, ferretdayo commented on NavigationForiOS/BeaconService.swift
> +        NSLog("didChangeAuthorizationStatus");
いらないーかな

2017-08-20 03:22 UTC, ferretdayo commented on NavigationForiOS/BeaconService.swift
> +        NSLog(" CLAuthorizationStatus: \(statusStr)")
いらないかな

2017-08-20 03:22 UTC, ferretdayo commented on NavigationForiOS/BeaconService.swift
> +        NSLog("didStartMonitoringForRegion");
いらないかな

2017-08-20 03:22 UTC, ferretdayo commented on NavigationForiOS/BeaconService.swift
> +    var beaconRegionArray = [CLBeaconRegion]()
Arrayという名前は変数名的には配列だろうと分かるけど，Arrayの名前自体に意味は余りなさそう．
Array消して，beaconRegionsと複数形にすれば，冗長じゃなくなくなる．

2017-08-20 03:22 UTC, ferretdayo commented on NavigationForiOS/BeaconService.swift
> +        NSLog("locationManager: didDetermineState \(state)")
いらないかな

2017-08-20 03:22 UTC, ferretdayo commented on NavigationForiOS/BeaconService.swift
> +            NSLog("CLRegionStateInside:");
いらないかな

2017-08-20 03:22 UTC, ferretdayo commented on NavigationForiOS/BeaconService.swift
> +        NSLog("\(beacons.count) detected!")
いらないかな

2017-08-20 03:22 UTC, ferretdayo commented on NavigationForiOS/BeaconService.swift
> +            NSLog("Max RSSI Beacon's minor id : \(maxRssiBeacon.minor)")
いらあにかな

2017-08-20 03:22 UTC, ferretdayo commented on NavigationForiOS/BeaconService.swift
> +        NSLog("didEnterRegion");
いらないかな

2017-08-20 03:22 UTC, ferretdayo commented on NavigationForiOS/BeaconService.swift
> +        NSLog("didExitRegion");
いらないかな

2017-08-20 03:22 UTC, ferretdayo commented on NavigationForiOS/BeaconService.swift
> +    func getUsingUUID() -> (String){
UUIDが増えた場合，実際これ使っているビーコンUUIDかわからないよね．
activeのUUIDを取得して，それを返すというようにしないと，厳密には違うと思う．

もしUUIDList自体が使用しているUUIDのリストであるなら，returnは配列のUUIDListになるのでは

2017-08-20 03:22 UTC, ferretdayo commented on NavigationForiOS/NavigationService.swift
> +                NSLog(error as! String)
いらないかな

2017-08-20 03:22 UTC, ferretdayo commented on NavigationForiOS/NavigationViewController.swift
> +            self.minor.text = "\(retval.minor)"
\()で囲む必要あるの？僕わからない

2017-08-20 03:48 UTC, Minajun commented on NavigationForiOS/BeaconService.swift
> +    func getUsingUUID() -> (String){
仕様上、UUIDを事前に指定しておかないと、受信してくれないから、無理

2017-08-20 03:49 UTC, Minajun commented on NavigationForiOS/BeaconService.swift
> +    func getUsingUUID() -> (String){
androidだったらできるけど、iosは指定しないと無理なので…

2017-08-20 03:51 UTC, Minajun commented on NavigationForiOS/NavigationViewController.swift
> +            self.minor.text = "\(retval.minor)"
癖というか、こうする派

2017-08-20 03:51 UTC, Minajun commented on NavigationForiOS/BeaconService.swift
> +    var beaconRegionArray = [CLBeaconRegion]()
かえます

2017-08-20 03:51 UTC, Minajun commented on NavigationForiOS/BeaconService.swift
> +        NSLog("Init BeaconService")
けします

2017-08-20 03:51 UTC, Minajun commented on NavigationForiOS/BeaconService.swift
> +            NSLog("CLAuthorizedStatus: \(status)")
けします

2017-08-20 03:51 UTC, Minajun commented on NavigationForiOS/BeaconService.swift
> +        NSLog("didChangeAuthorizationStatus");
けします

2017-08-20 03:52 UTC, Minajun commented on NavigationForiOS/BeaconService.swift
> +        NSLog(" CLAuthorizationStatus: \(statusStr)")
けします

2017-08-20 03:52 UTC, Minajun commented on NavigationForiOS/BeaconService.swift
> +        NSLog("didStartMonitoringForRegion");
けします

2017-08-20 03:52 UTC, Minajun commented on NavigationForiOS/BeaconService.swift
> +        NSLog("locationManager: didDetermineState \(state)")
けします

2017-08-20 03:52 UTC, Minajun commented on NavigationForiOS/BeaconService.swift
> +            NSLog("CLRegionStateInside:");
けします

2017-08-20 05:41 UTC, ferretdayo commented on NavigationForiOS/NavigationViewController.swift
> +            self.minor.text = "\(retval.minor)"
ごめん　"\(retval.minor)"のところ

2017-08-20 06:03 UTC, Minajun commented on NavigationForiOS/NavigationViewController.swift
> +            self.minor.text = "\(retval.minor)"
retail.minorはInt型だから、テキストで出すためにStringに変換しないといけないからそうしているわけで

2017-08-20 06:05 UTC, ferretdayo commented on NavigationForiOS/NavigationViewController.swift
> +            self.minor.text = "\(retval.minor)"
あーなるほど as Stringとかジャー無理なのか

2017-08-20 06:07 UTC, Minajun commented on NavigationForiOS/NavigationViewController.swift
> +            self.minor.text = "\(retval.minor)"
as Stringでもいけるっぽいけど、こっちで書く方に慣れちゃってる

2017-08-20 06:08 UTC, Minajun commented on NavigationForiOS/NavigationViewController.swift
> +            self.minor.text = "\(retval.minor)"
てか、数字だけ出力しても、何の値かわからんな

2017-08-20 06:41 UTC, ferretdayo commented
![dhb75w_uqae3ci0](https://user-images.githubusercontent.com/5894431/29492652-042b6390-85be-11e7-94fb-8fa110c921f9.jpg)

2017-08-20 06:41 UTC, ferretdayo submitted a review, later dismissed

2017-08-21 07:54 UTC, Minajun commented
実機での動作確認のスクショ
![screen shot 2017-08-21 at 16 46 53](https://user-images.githubusercontent.com/18542039/29508922-5d5ee13e-8691-11e7-8d93-254377016ceb.png)
![screen shot 2017-08-21 at 16 47 20](https://user-images.githubusercontent.com/18542039/29508923-5d6e4a98-8691-11e7-8415-c19888f8326e.png)

2017-08-21 08:05 UTC, ferretdayo approved these changes
breakはまかせる

2017-08-21 08:05 UTC, ferretdayo commented on NavigationForiOS/BeaconService.swift
> +            break
swift3の場合 breakはデフォでつくので，書かなくていいらしい．
みんな慣れないならbreak書いてもいいかもね

2017-08-21 08:05 UTC, ferretdayo commented on NavigationForiOS/BeaconService.swift
> +            break
breakを描くか書かないか

2017-08-21 11:19 UTC, merged