[WIP]#54目的地に到着したことに気づける
tsukuba-pbl/NavigationFor_iOS pull request #22
Opened 2017-08-21 11:42 UTC by Minajun

# ユーザーストーリー
#54目的地に到着したことに気づける
https://tree.taiga.io/project/minajun-tsukuba-rd-project-2017-ume-systems/us/54?milestone=146595

## TODO
- [ ] ナビゲーション情報に、スタート・ゴール属性を追加
- [ ] 目的地のビーコンに近づいた時に、到着したことを画面上に表示させる
- [ ] ナビゲーションが終了したら、前の画面（目的地選択画面）に戻る

# 終了条件
- [ ] 目的地に到着したら、ナビゲーションが終了し、目的地選択画面に戻っていること
- [ ] テストが通っていること

# 前提条件
- [ ] ナビゲーションデータは事前に用意されている

2017-08-23 06:59 UTC, Minajun commented on NavigationForiOS/NavigationService.swift
> +                    print("\(minor):\(navigation)")
あとで削除

2017-08-23 07:00 UTC, Minajun commented on NavigationForiOS/NavigationService.swift
> +                goal_minor_id = navJson["goal"].int!
本当は、navJson["start"]["minor"]ってしたかったけど、なぜかできんかった

2017-08-23 07:00 UTC, Minajun commented on NavigationForiOS/NavigationViewController.swift
> +                    }
あとで、この処理を分ける方がいいかもな〜

2017-08-23 07:01 UTC, Minajun commented on NavigationForiOS/NavigationService.swift
> +        print(goal_minor_id)
あとで削除

2017-08-23 07:02 UTC, ferretdayo requested changes
╮(´･ᴗ･` )╭

2017-08-23 07:02 UTC, ferretdayo commented on NavigationForiOS/NavigationService.swift
> +    static func getNavigationJSON(responseNavigations: @escaping (Dictionary<Int,String>) -> Void){
正確に言うと，`getNavigationJSON()`じゃないよね．これだとこのメソッドを使う側はJSONが返ってくるのかと思うよね．
今回だとなんだろう．前のままでもいいと思ったりもするけどね．

2017-08-23 07:02 UTC, ferretdayo commented on NavigationForiOS/NavigationService.swift
> +    static func getNavigationJSON(responseNavigations: @escaping (Dictionary<Int,String>) -> Void){
getNavigationRoutesでもいいかも？わからんけど

2017-08-23 07:02 UTC, ferretdayo commented on NavigationForiOS/NavigationService.swift
> +                    print("\(minor):\(navigation)")
╮(´･ᴗ･` )╭

2017-08-23 07:02 UTC, ferretdayo commented on NavigationForiOS/NavigationService.swift
> +        print(goal_minor_id)
╮(´･ᴗ･` )╭

2017-08-23 07:02 UTC, ferretdayo commented on NavigationForiOS/NavigationViewController.swift
> +        let alertController = UIAlertController(title: "Navigation",message: "目的地に到着しました", preferredStyle: UIAlertControllerStyle.alert)
,の後に半角スペース欲しい

2017-08-23 07:02 UTC, ferretdayo commented on NavigationForiOS/NavigationViewController.swift
> +            self.present(next,animated: true, completion: nil)
,の後に半角スペース欲しい

2017-08-23 07:02 UTC, ferretdayo commented on NavigationForiOS/NavigationViewController.swift
> +        present(alertController,animated: true,completion: nil)
,の後に（ｒｙ

2017-08-23 07:02 UTC, ferretdayo commented on NavigationForiOS/NavigationService.swift
> +    static var navigations = [Int: String]()
NavigationServiceに状態をもたせるのはなんだかなぁと思ったりするのですが，どう思いますか．
NavigationEntityみたいなクラス作って，ナビゲーション情報を持たせるものをありなんかな

2017-08-23 07:05 UTC, Minajun commented on NavigationForiOS/NavigationService.swift
> +    static func getNavigationJSON(responseNavigations: @escaping (Dictionary<Int,String>) -> Void){
たしかし

2017-08-23 07:05 UTC, Minajun commented on NavigationForiOS/NavigationService.swift
> +    static func getNavigationJSON(responseNavigations: @escaping (Dictionary<Int,String>) -> Void){
ルート情報だけじゃないから、getNavigationData()にするわ

2017-08-23 09:10 UTC, Minajun commented on NavigationForiOS/NavigationService.swift
>                      //Dictionaryにペアとして追加（key:minor val:navigation）
このコメント変えるの忘れてた

2017-08-23 09:11 UTC, Minajun commented on NavigationForiOS/NavigationViewController.swift
>          }
レスポンスいらないんだけど、このときどう書けばいいかわからんから、空白

2017-08-23 09:12 UTC, Minajun commented on NavigationForiOS/NavigationViewController.swift
>              if(isOnNavigationPoint(RSSI: retval.rssi, uuid: UUID(uuidString : retval.uuid)!, threshold: -80)){
ここからの判定を、fixブランチでNavigationServiceに移動したい

2017-08-23 09:12 UTC, ferretdayo requested changes
╮(´･ᴗ･` )╭

2017-08-23 09:12 UTC, ferretdayo commented on NavigationForiOS/NavigationEntity.swift
> +    func addPoint(minor_id : Int, threshold : Int, navigation_text : String, type: Int){
addPointをaddNavigationPointの方が良いのでは？わからんけど

2017-08-23 09:12 UTC, ferretdayo commented on NavigationForiOS/NavigationEntity.swift
> +    func isAbailableId(id : Int) -> Bool{
isAbailableBeaconIdの方がいいかも

2017-08-23 09:12 UTC, ferretdayo commented on NavigationForiOS/NavigationEntity.swift
> +    var bAvailable = false //ルート情報が有効かどうか
bってbeaconのこと？略さないほうがいいと思う

2017-08-23 09:12 UTC, ferretdayo commented on NavigationForiOS/NavigationViewController.swift
> +        NavigationService.getNavigationData{response in
なんかresponse使わなくなると悲しくなるね．
NavigationServiceの`static let navigations = NavigationEntity()`をNavigationViewControllerに書いて，responseをnavigationsにしたらよさそう．
Serviceには状態を持たないほうがいいと思う（ごめん理由はない）

2017-08-23 09:14 UTC, Minajun commented on NavigationForiOS/NavigationEntity.swift
> +    var bAvailable = false //ルート情報が有効かどうか
先頭にbつけてるのは、booleanのときにしてたりする

2017-08-23 09:14 UTC, Minajun commented on NavigationForiOS/NavigationEntity.swift
> +    func addPoint(minor_id : Int, threshold : Int, navigation_text : String, type: Int){
そうするわ

2017-08-23 09:15 UTC, ferretdayo commented on NavigationForiOS/NavigationViewController.swift
>              if(isOnNavigationPoint(RSSI: retval.rssi, uuid: UUID(uuidString : retval.uuid)!, threshold: -80)){
お　よさそう

2017-08-23 09:16 UTC, Minajun commented on NavigationForiOS/NavigationViewController.swift
> +        NavigationService.getNavigationData{response in
自分の中では、NavigationServiceの中に、データとそれに関連する処理を記述するものかと思ってるんだけど、どうなんだろう
ViewControllerに変数が大量に溢れそうだし

2017-08-23 09:17 UTC, ferretdayo commented on NavigationForiOS/NavigationEntity.swift
> +    var bAvailable = false //ルート情報が有効かどうか
それはわからなかったｗｗｗ
それならisAvailableがいいと思う．
あれ availableの単語が分からない間違ってるところあった気がする

2017-08-23 09:32 UTC, ferretdayo commented on NavigationForiOS/NavigationEntity.swift
> +    func isAbailableBeaconId(id : Int) -> Bool{
ここだスペルミス

2017-08-23 12:41 UTC, ferretdayo commented on NavigationForiOS/NavigationViewController.swift
> +        NavigationService.getNavigationData{response in
> NavigationServiceの中に、データとそれに関連する処理を記述するものかと思ってるんだけど、どうなんだろう
> ViewControllerに変数が大量に溢れそうだし

それは分かるんだけど，
うーん．`getNavigationData()`を呼び出して，何もreturnされないのは名前が変だしなぁ．
それと，サービスって利用者に何かを提供してくれるイメージなんだよね．returnがないのはサービスとして微妙だよなーという．`isAvailableBeacon()`は利用者が「このビーコン使えますか？大丈夫です？」という問いかけに対して，サービスは「あっこれは使えますよー」と教えてくれるからサービスとして成り立ってるよねとかとか

2017-08-24 04:07 UTC, ferretdayo commented on NavigationForiOS/BeaconService.swift
> +        self.navigations = navigations
navigationsは `orverride init()`のコンストラクタで初期化したさある．
startBeaconReceiverを最初に動かすのは分かるけど，コンストラクタはこのクラスを利用する上で絶対最初に動くので，そこで初期化？の方が尤もらしいと感じる

2017-08-24 04:07 UTC, ferretdayo commented on NavigationForiOS/NavigationController.swift
> +class NavigationController{
NavigationViewControllerがあるからいいかなと思ったけど，NavigationController作ったらいい感じやな :+1:

2017-08-24 04:07 UTC, ferretdayo commented on NavigationForiOS/NavigationController.swift
> +    func getNavigation(){
initNavigationの方が良さそう
`init()`の中でgetNavigation()だとgetなんちゃらメソッドなのに，returnないの？となっちゃいそう

2017-08-24 04:12 UTC, Minajun commented on NavigationForiOS/BeaconService.swift
> +        self.navigations = navigations
コンストラクタにした、エラーが出てできなかったから仕方なくこうやった

2017-08-24 04:15 UTC, ferretdayo commented on NavigationForiOS/BeaconService.swift
> +        self.navigations = navigations
かなしみ

2017-08-24 04:16 UTC, Minajun commented on NavigationForiOS/BeaconService.swift
> +        self.navigations = navigations
このままでいい？

2017-08-24 04:17 UTC, ferretdayo commented on NavigationForiOS/BeaconService.swift
> +        self.navigations = navigations
ひとまずそうだね

2017-08-24 05:20 UTC, ferretdayo approved these changes
ええんやない？

2017-08-24 05:21 UTC, merged