[WIP]平滑化されたビーコンの電波強度が取得できる
tsukuba-pbl/NavigationFor_iOS pull request #40
Opened 2017-08-29 03:44 UTC by Minajun

ISSUE : #37

2017-08-29 17:55 UTC, ferretdayo requested changes
# ポエム
BeaconEntityを作って
- rssi
- uuid
- minorId
の状態をもたせたほうがいいかも．
そうすると関数の引数が今rssi, uuid, minorIdみたいになってるけど，beaconEntityの１つで終わるし

2017-08-29 17:55 UTC, ferretdayo commented on NavigationForiOS/BeaconService.swift
> +    var oldbeaconsRssiList = Dictionary<Int, Int>()
細かいが，`oldBeaconsRssiList`とbを大文字のほうが

2017-08-29 17:55 UTC, ferretdayo commented on NavigationForiOS/BeaconService.swift
> +    var beaconsRssiList = Dictionary<Int, Int>() //key:minor(int val) val:rssi(int val)
`beacons`じゃなくていいのでは`List`でbeaconのrssiが複数なのは分かるので，
`oldbeaconsRssiList`も同様

2017-08-29 17:55 UTC, ferretdayo commented on NavigationForiOS/BeaconService.swift
> +        var receiveBeaconRssiList = beaconsRssiList
`beaconsRssiList`ってJSONで取ってきた，利用している全てのビーコン情報リスト？
そうであるなら，`allBeaconRssiList`とかのほうがわかりやすいかも

2017-08-29 17:55 UTC, ferretdayo commented on NavigationForiOS/BeaconService.swift
> +            //BeaconRssiListに格納
コメント間違ってない？

2017-08-29 17:55 UTC, ferretdayo commented on NavigationForiOS/BeaconService.swift
> +    func getMaxRssiBeacon() -> (flag : Bool, minor : Int, rssi : Int){
そういやこのflagってどういうフラグなの？flagだけだといろんな予想ができるので，できれば具体化してほしいかも

2017-08-29 17:55 UTC, ferretdayo commented on NavigationForiOS/BeaconService.swift
> +    func LPF(current_beacons_rssi_list: Dictionary<Int, Int>, old_beacons_rssi_list: Dictionary<Int, Int>) -> Dictionary<Int, Int> {
`beacons`じゃなく`beacon`では？listが後ろについてるので複数なのが分かる

2017-08-29 17:55 UTC, ferretdayo commented on NavigationForiOS/BeaconService.swift
> +        var z = current_beacons_rssi_list
`z`に退避するのではなく，
```
var resultBeaconRssiList: Dictionary<Int, Int>()
let alpha = 0.7

for i in current_beacon_rssi_list {
  let lpfedRssi = Double(old_....)
  resultBeaconRssiList[i.key] = lpfedRssi
}
return resultBeaconRssiList
```
とかでは駄目なのかな？current_beacons_rssi_listを代入したやつをupdateValueするの個人的に読みづらいなぁと思ってしまう．本来コピーってするものではないのでは？と思ったり．意味的には別物なきがするので

2017-08-29 17:55 UTC, ferretdayo commented on NavigationForiOSTests/BeaconServiceTests.swift
> +            XCTAssertEqual(Int((Double(current[key]!)*alpha) + (Double(old[key]!)*(1.0-alpha))), retval[key])
これテストとして成り立ってない気がする．
関数の中の計算方法(`(Double(current[key]!)*alpha) + (Double(old[key]!)*(1.0-alpha)`)を，左に書いてるだけなので，そりゃーテスト通るテストになっている．

どっちかというと，手計算のやつを関数で計算した値の照らし合わしがテストかな

2017-08-29 18:00 UTC, ferretdayo commented on NavigationForiOS/BeaconService.swift
> +        var receiveBeaconRssiList = beaconsRssiList
allも微妙かな・・・

2017-08-29 18:00 UTC, ferretdayo commented on NavigationForiOS/BeaconService.swift
> +    func LPF(current_beacons_rssi_list: Dictionary<Int, Int>, old_beacons_rssi_list: Dictionary<Int, Int>) -> Dictionary<Int, Int> {
ここだけ，スネークケースになっているの気になる

2017-08-30 02:55 UTC, Minajun commented on NavigationForiOS/BeaconService.swift
> +        var receiveBeaconRssiList = beaconsRssiList
使用しているビーコンと、その受信したRSSIの情報がここに入る

2017-08-30 02:56 UTC, Minajun commented on NavigationForiOS/BeaconService.swift
> +        var receiveBeaconRssiList = beaconsRssiList
まあ、適当に名前変えるわ

2017-08-30 03:06 UTC, Minajun commented on NavigationForiOS/BeaconService.swift
> +    var beaconsRssiList = Dictionary<Int, Int>() //key:minor(int val) val:rssi(int val)
やった

2017-08-30 03:06 UTC, Minajun commented on NavigationForiOS/BeaconService.swift
> +    var oldbeaconsRssiList = Dictionary<Int, Int>()
やった

2017-08-30 03:07 UTC, Minajun commented on NavigationForiOS/BeaconService.swift
> +        var receiveBeaconRssiList = beaconsRssiList
やった

2017-08-30 03:08 UTC, Minajun commented on NavigationForiOS/BeaconService.swift
> +            //BeaconRssiListに格納
コメント消す

2017-08-30 03:10 UTC, Minajun commented on NavigationForiOS/BeaconService.swift
> +    func getMaxRssiBeacon() -> (flag : Bool, minor : Int, rssi : Int){
yatta

2017-08-30 03:12 UTC, Minajun commented on NavigationForiOS/BeaconService.swift
> +    func LPF(current_beacons_rssi_list: Dictionary<Int, Int>, old_beacons_rssi_list: Dictionary<Int, Int>) -> Dictionary<Int, Int> {
鈴木くんとペアプロしたから、それぞれの書き方によって違うからこうなった
コーディング規則とか決めてないし、こうなっても仕方ないのでは？
（直すけど）

2017-08-30 13:57 UTC, ferretdayo approved these changes
いいと思います

2017-08-30 14:20 UTC, merged